export const products = [
    {
      id: 1,
      title: "Men Sport Shoe MO 508",
      price: "16.00 ₪",
      oldPrice: "70",
      image: "https://cdn.mart.ps/169825-large_default/men-sport-shoe-mo-508.jpg",
      url: "https://mart.ps/men-sport-shoe/56500-men-sport-shoe-mo-508.html",
      productRef: "10316507",
     },
     {
        id: 2,
        title: "حذاء فاشن سبورت رياضي للجنسين لون أسود وبرتقالي",
        price: "16.00 ₪",
        oldPrice: "40",
        image: "https://cdn.mart.ps/223640-large_default/حذاء-فاشن-سبورت-رياضي-للجنسين-لون-أسود-وبرتقالي.jpg",
        url: "https://mart.ps/men-sport-shoe/69245-حذاء-فاشن-سبورت-رياضي-للجنسين-لون-أسود-وبرتقالي.html",
        productRef: "10328874",
      },
      {
        id: 3,
        title: "حذاء كاجوال نسيج للرجال لون رمادي",
        price: "33.00 ₪",
        oldPrice: "120",
        image: "https://cdn.mart.ps/238733-large_default/حذاء-كاجوال-نسيج-للرجال-لون-رمادي.jpg",
        url: "https://mart.ps/men-sport-shoe/72562-حذاء-كاجوال-نسيج-للرجال-لون-رمادي.html",
        productRef: "10332178",
      },
      {
        id: 4,
        title: "حذاء كاجيوال سبورت للشباب",
        price: "33.00 ₪",
        oldPrice: "100",
        image: "https://cdn.mart.ps/197278-large_default/حذاء-كاجيوال-سبورت-للشباب.jpg",
        url: "https://mart.ps/men-sport-shoe/62405-حذاء-كاجيوال-سبورت-للشباب.html",
        productRef: "10322123",
      },
      {
        id: 5,
        title: "Men Sport Shoe MO 508",
        price: "16.00 ₪",
        oldPrice: "70",
        image: "https://cdn.mart.ps/169825-large_default/men-sport-shoe-mo-508.jpg",
        url: "https://mart.ps/men-sport-shoe/56500-men-sport-shoe-mo-508.html",
        productRef: "10316507",
       },
      {
        id: 6,
        title: "Men Sport Shoe MO 508",
        price: "16.00 ₪",
        oldPrice: "70",
        image: "https://cdn.mart.ps/169825-large_default/men-sport-shoe-mo-508.jpg",
        url: "https://mart.ps/men-sport-shoe/56500-men-sport-shoe-mo-508.html",
        productRef: "10316507",
       },
      {
        id: 7,
        title: "Men Sport Shoe MO 508",
        price: "16.00 ₪",
        oldPrice: "70",
        image: "https://cdn.mart.ps/169825-large_default/men-sport-shoe-mo-508.jpg",
        url: "https://mart.ps/men-sport-shoe/56500-men-sport-shoe-mo-508.html",
        productRef: "10316507",
       },
      {
          id: 8,
          title: "Men Sport Shoe MO 508",
          price: "16.00 ₪",
          oldPrice: "70",
          image: "https://cdn.mart.ps/169825-large_default/men-sport-shoe-mo-508.jpg",
          url: "https://mart.ps/men-sport-shoe/56500-men-sport-shoe-mo-508.html",
          productRef: "10316507",
         },
        {
          id: 9,
          title: "Men Sport Shoe MO 508",
          price: "16.00 ₪",
          oldPrice: "70",
          image: "https://cdn.mart.ps/169825-large_default/men-sport-shoe-mo-508.jpg",
          url: "https://mart.ps/men-sport-shoe/56500-men-sport-shoe-mo-508.html",
          productRef: "10316507",
         },
        {
          id: 10,
          title: "Men Sport Shoe MO 508",
          price: "16.00 ₪",
          oldPrice: "70",
          image: "https://cdn.mart.ps/169825-large_default/men-sport-shoe-mo-508.jpg",
          url: "https://mart.ps/men-sport-shoe/56500-men-sport-shoe-mo-508.html",
          productRef: "10316507",
         },
        {
          id: 11,
          title: "Men Sport Shoe MO 508",
          price: "16.00 ₪",
          oldPrice: "70",
          image: "https://cdn.mart.ps/169825-large_default/men-sport-shoe-mo-508.jpg",
          url: "https://mart.ps/men-sport-shoe/56500-men-sport-shoe-mo-508.html",
          productRef: "10316507",
         },
        {
          id: 12,
          title: "Men Sport Shoe MO 508",
          price: "16.00 ₪",
          oldPrice: "70",
          image: "https://cdn.mart.ps/169825-large_default/men-sport-shoe-mo-508.jpg",
          url: "https://mart.ps/men-sport-shoe/56500-men-sport-shoe-mo-508.html",
          productRef: "10316507",
         },
   ];
  